source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLForm_Example' do
  pod "PLForm", :path => "../"
  pod 'IQKeyboardManager'
  pod 'Reveal-SDK', :configurations => ['Debug']
  pod 'libPhoneNumber-iOS'

  target 'PLForm_Tests' do
	 inherit! :search_paths

  end

end
